[project]
name = "llm-zoomcamp-evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.31.0",
    "jupyter>=1.1.1",
    "minsearch>=0.0.8",
    "openai>=2.48.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]

[project.scripts]
llm-zoomcamp-evaluation = "llm_zoomcamp_evaluation:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
